{{- if .Values.alembic.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fastapi-helm-chart.fullname" . }}-migrate
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "fastapi-helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade          
    "helm.sh/hook-weight": "0"                       
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300                       
  backoffLimit: 1                                    
  template:
    metadata:
      annotations:
        {{- include "fastapi-helm-chart.defaultPodAnnotations" . | nindent 8 }}
        {{- with .Values.alembic.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "fastapi-helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.alembic.podSecurityContext | nindent 8 }}
      restartPolicy: OnFailure
      containers:
        - name: alembic
          securityContext:
            {{- toYaml .Values.alembic.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic"]
          args: ["-c", "/home/app/alembic/alembic.ini", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: {{ include "fastapi-helm-chart.fullname" . }}
            - secretRef:
                name: {{ include "fastapi-helm-chart.fullname" . }}
{{- end }}
