apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "fastapi-helm-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap | nindent 2 }}
