{{- if .Values.webDeployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-helm-chart.fullname" . }}-web
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "fastapi-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webDeployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "fastapi-helm-chart.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webDeployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fastapi-helm-chart.webSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fastapi-helm-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webDeployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "fastapi-helm-chart.fullname" . }}
          securityContext:
            {{- toYaml .Values.webDeployment.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.webDeployment.command }}
          command: {{ .Values.webDeployment.command }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "fastapi-helm-chart.fullname" . }}
            - secretRef:
                name: {{ include "fastapi-helm-chart.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.webDeployment.resources | nindent 12 }}
{{- end }}
