{{- if .Values.webDeployment.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fastapi-helm-chart.fullname" . }}-web
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "fastapi-helm-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.webDeployment.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.webDeployment.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if .Values.webDeployment.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.webDeployment.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fastapi-helm-chart.webSelectorLabels" . | nindent 6 }}
{{- end }}
