apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "fastapi-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
