{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fastapi-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "fastapi-helm-chart.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | default .Values.namespace }}
  selector:
    matchLabels:
      {{- include "fastapi-helm-chart.labels" . | nindent 6 }}
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scheme: http
{{- end }}
